map.createObject(26, 19).setSprite("rocket").setDirection("LEFT").onUse(function(player) possiblyBattleROCKET_HIDEOUT_1_26_19(player, true) end)
map.createObject(25, 19).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_26_19(player, false) end)
map.createObject(24, 19).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_26_19(player, false) end)
map.createObject(23, 19).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_26_19(player, false) end)
function possiblyBattleROCKET_HIDEOUT_1_26_19(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCKET_HIDEOUT_1_26_19", "ROCKET", "rocket", {{21, "DROWZEE"}, {21, "MACHOP"}}, 'Who are you? How\ndid you get here?', 'Are you dissing\nTEAM ROCKET?', 'Oww!\nBeaten!')
end
map.createObject(12, 21).setSprite("rocket").setDirection("RIGHT").onUse(function(player) possiblyBattleROCKET_HIDEOUT_1_12_21(player, true) end)
map.createObject(13, 21).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_12_21(player, false) end)
map.createObject(14, 21).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_12_21(player, false) end)
function possiblyBattleROCKET_HIDEOUT_1_12_21(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCKET_HIDEOUT_1_12_21", "ROCKET", "rocket", {{21, "RATICATE"}, {21, "RATICATE"}}, 'You broke into\nour operation?', "You're not going\nto get away with\nthis, brat!", 'Burnt!')
end
map.createObject(18, 10).setSprite("rocket").setDirection("DOWN").onUse(function(player) possiblyBattleROCKET_HIDEOUT_1_18_10(player, true) end)
map.createObject(18, 9).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_18_10(player, false) end)
map.createObject(18, 8).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_18_10(player, false) end)
function possiblyBattleROCKET_HIDEOUT_1_18_10(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCKET_HIDEOUT_1_18_10", "ROCKET", "rocket", {{20, "GRIMER"}, {20, "KOFFING"}, {20, "KOFFING"}}, 'Intruder alert!', "SILPH SCOPE?\nI don't know\nwhere it is!", "I\ncan't do it!")
end
map.createObject(15, 2).setSprite("rocket").setDirection("RIGHT").onUse(function(player) possiblyBattleROCKET_HIDEOUT_1_15_2(player, true) end)
map.createObject(16, 2).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_15_2(player, false) end)
map.createObject(17, 2).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_15_2(player, false) end)
map.createObject(18, 2).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_15_2(player, false) end)
function possiblyBattleROCKET_HIDEOUT_1_15_2(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCKET_HIDEOUT_1_15_2", "ROCKET", "rocket", {{19, "RATTATA"}, {19, "RATICATE"}, {19, "RATICATE"}, {19, "RATTATA"}}, 'Why did you come\nhere?', "OK, I'll talk!\nTake the elevator\nto see my BOSS!", "This\nwon't do!")
end
map.createObject(28, 9).setSprite("rocket").setDirection("LEFT").onUse(function(player) possiblyBattleROCKET_HIDEOUT_1_28_9(player, true) end)
map.createObject(27, 9).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_28_9(player, false) end)
map.createObject(26, 9).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_28_9(player, false) end)
map.createObject(25, 9).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_1_28_9(player, false) end)
function possiblyBattleROCKET_HIDEOUT_1_28_9(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCKET_HIDEOUT_1_28_9", "ROCKET", "rocket", {{22, "GRIMER"}, {22, "KOFFING"}}, 'Are you lost, you\nlittle rat?', 'Uh-oh, that fight\nopened the door!', 'Why...?@@')
end
map.createObject(11, 13).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "ROCKET_HIDEOUT_1_11_13", "ESCAPE ROPE") end)
map.createObject(9, 10).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "ROCKET_HIDEOUT_1_9_10", "HYPER POTION") end)
