map.createObject(10, 5).setSprite("rocket").setDirection("RIGHT").onUse(function(player) possiblyBattleROCKET_HIDEOUT_3_10_5(player, true) end)
map.createObject(11, 5).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_3_10_5(player, false) end)
map.createObject(12, 5).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_3_10_5(player, false) end)
function possiblyBattleROCKET_HIDEOUT_3_10_5(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCKET_HIDEOUT_3_10_5", "ROCKET", "rocket", {{20, "RATTATA"}, {20, "RATICATE"}, {20, "DROWZEE"}}, "Stop meddling in\nTEAM ROCKET's\naffairs!", "SILPH SCOPE?\nThe machine the\nBOSS stole. It's\nhere somewhere.", 'Oof!\nTaken down!')
end
map.createObject(26, 15).setSprite("rocket").setDirection("UP").onUse(function(player) possiblyBattleROCKET_HIDEOUT_3_26_15(player, true) end)
map.createObject(26, 16).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_3_26_15(player, false) end)
map.createObject(26, 17).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_3_26_15(player, false) end)
map.createObject(26, 18).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_3_26_15(player, false) end)
map.createObject(26, 19).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_3_26_15(player, false) end)
function possiblyBattleROCKET_HIDEOUT_3_26_15(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCKET_HIDEOUT_3_26_15", "ROCKET", "rocket", {{21, "MACHOP"}, {21, "MACHOP"}}, 'We got word from\nupstairs that you\nwere coming!', 'Go ahead and go!\nBut, you need the\nLIFT KEY to run\nthe elevator!', 'What?\nI lost? No!')
end
map.createObject(26, 10).setSprite("ball").onUse(function(player) attemptToPickupObject("ROCKET_HIDEOUT_3_26_10", "TM 10") end)
map.createObject(20, 13).setSprite("ball").onUse(function(player) attemptToPickupObject("ROCKET_HIDEOUT_3_20_13", "RARE CANDY") end)
