map.createObject(2, 16).setSprite("giovanni").setDirection("DOWN")--[[NO HEADER: .onUse(function(player)
    checkForTrainerBattle(player, true, "VIRIDIAN_GYM_2_16", "GIOVANNI", "giovanni", {{45, "RHYHORN"}, {42, "DUGTRIO"}, {44, "NIDOQUEEN"}, {45, "NIDOKING"}, {50, "RHYDON"}}, '?', '?', '?')
end)--]]
map.createObject(12, 10).setSprite("black_hair_boy_1").setDirection("DOWN").onUse(function(player) possiblyBattleVIRIDIAN_GYM_12_10(player, true) end)
map.createObject(12, 9).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_12_10(player, false) end)
map.createObject(12, 8).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_12_10(player, false) end)
map.createObject(12, 7).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_12_10(player, false) end)
map.createObject(12, 6).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_12_10(player, false) end)
function possiblyBattleVIRIDIAN_GYM_12_10(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "VIRIDIAN_GYM_12_10", "COOLTRAINER#MALE", "cooltrainerm", {{39, "SANDSLASH"}, {39, "DUGTRIO"}}, 'Heh! You must be\nrunning out of\nsteam by now!', 'You need power to\nkeep up with our\nGYM LEADER!', 'I\nran out of gas!')
end
map.createObject(11, 6).setSprite("hiker").setDirection("UP").onUse(function(player) possiblyBattleVIRIDIAN_GYM_11_6(player, true) end)
map.createObject(11, 7).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_11_6(player, false) end)
map.createObject(11, 8).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_11_6(player, false) end)
map.createObject(11, 9).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_11_6(player, false) end)
map.createObject(11, 10).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_11_6(player, false) end)
function possiblyBattleVIRIDIAN_GYM_11_6(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "VIRIDIAN_GYM_11_6", "BLACKBELT", "blackbelt", {{40, "MACHOP"}, {40, "MACHOKE"}}, "Rrrroar! I'm\nworking myself\ninto a rage!", "I'm still not\nworthy!", 'Wargh!')
end
map.createObject(10, 10).setSprite("rocker").setDirection("DOWN").onUse(function(player) possiblyBattleVIRIDIAN_GYM_10_10(player, true) end)
map.createObject(10, 9).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_10_10(player, false) end)
map.createObject(10, 8).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_10_10(player, false) end)
map.createObject(10, 7).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_10_10(player, false) end)
map.createObject(10, 6).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_10_10(player, false) end)
function possiblyBattleVIRIDIAN_GYM_10_10(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "VIRIDIAN_GYM_10_10", "TAMER", "tamer", {{43, "RHYHORN"}}, 'POKEMON and I, we\nmake wonderful\nmusic together!', 'Do you know the\nidentity of our\nGYM LEADER?', 'You are in\nperfect harmony!')
end
map.createObject(3, 10).setSprite("hiker").setDirection("LEFT").onUse(function(player) possiblyBattleVIRIDIAN_GYM_3_10(player, true) end)
map.createObject(2, 10).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_3_10(player, false) end)
map.createObject(1, 10).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_3_10(player, false) end)
function possiblyBattleVIRIDIAN_GYM_3_10(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "VIRIDIAN_GYM_3_10", "BLACKBELT", "blackbelt", {{43, "MACHOKE"}}, 'Karate is the\nultimate form of\nmartial arts!', 'If my POKEMON\nwere as good at\nKarate as I...', 'Atcho!')
end
map.createObject(13, 12).setSprite("black_hair_boy_1").setDirection("RIGHT").onUse(function(player) possiblyBattleVIRIDIAN_GYM_13_12(player, true) end)
map.createObject(14, 12).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_13_12(player, false) end)
map.createObject(15, 12).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_13_12(player, false) end)
map.createObject(16, 12).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_13_12(player, false) end)
function possiblyBattleVIRIDIAN_GYM_13_12(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "VIRIDIAN_GYM_13_12", "COOLTRAINER#MALE", "cooltrainerm", {{43, "RHYHORN"}}, 'The truly talented\nwin with style!', 'The LEADER will\nscold me!', 'I\nlost my grip!')
end
map.createObject(10, 16).setSprite("hiker").setDirection("DOWN").onUse(function(player) possiblyBattleVIRIDIAN_GYM_10_16(player, true) end)
map.createObject(10, 15).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_10_16(player, false) end)
map.createObject(10, 14).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_10_16(player, false) end)
map.createObject(10, 13).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_10_16(player, false) end)
map.createObject(10, 12).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_10_16(player, false) end)
function possiblyBattleVIRIDIAN_GYM_10_16(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "VIRIDIAN_GYM_10_16", "BLACKBELT", "blackbelt", {{38, "MACHOKE"}, {38, "MACHOP"}, {38, "MACHOKE"}}, "I'm the KARATE\nKING! Your fate\nrests with me!", "POKEMON LEAGUE?\nYou? Don't get\ncocky!", 'Ayah!')
end
map.createObject(2, 1).setSprite("rocker").setDirection("RIGHT").onUse(function(player) possiblyBattleVIRIDIAN_GYM_2_1(player, true) end)
map.createObject(3, 1).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_2_1(player, false) end)
map.createObject(4, 1).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_2_1(player, false) end)
map.createObject(5, 1).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_2_1(player, false) end)
function possiblyBattleVIRIDIAN_GYM_2_1(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "VIRIDIAN_GYM_2_1", "TAMER", "tamer", {{39, "ARBOK"}, {39, "TAUROS"}}, 'Your POKEMON will\ncower at the\ncrack of my whip!', 'Wait! I was just\ncareless!', 'Yowch!\nWhiplash!')
end
map.createObject(6, 12).setSprite("black_hair_boy_1").setDirection("DOWN").onUse(function(player) possiblyBattleVIRIDIAN_GYM_6_12(player, true) end)
map.createObject(6, 11).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_6_12(player, false) end)
map.createObject(6, 10).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_6_12(player, false) end)
map.createObject(6, 9).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_6_12(player, false) end)
map.createObject(6, 8).onTouch(function(player) possiblyBattleVIRIDIAN_GYM_6_12(player, false) end)
function possiblyBattleVIRIDIAN_GYM_6_12(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "VIRIDIAN_GYM_6_12", "COOLTRAINER#MALE", "cooltrainerm", {{39, "NIDORINO"}, {39, "NIDOKING"}}, 'VIRIDIAN GYM was\nclosed for a long\ntime, but now our\nLEADER is back!', 'You can go onto\nPOKEMON LEAGUE\nonly by defeating\nour GYM LEADER!', 'I\nwas beaten?')
end
map.createObject(16, 2).setSprite("gym_helper").setDirection("DOWN")--[[['10 ; person']--]]
map.createObject(16, 8).setSprite("ball").onUse(function(player) attemptToPickupObject("VIRIDIAN_GYM_16_8", "REVIVE") end)
