map.createObject(20, 25).onTouch(function(player) player.teleportTo("SAFARI_ZONE_NORTH", 2, 0) end)
map.createObject(21, 25).onTouch(function(player) player.teleportTo("SAFARI_ZONE_NORTH", 3, 0) end)
map.createObject(26, 25).onTouch(function(player) player.teleportTo("SAFARI_ZONE_NORTH", 8, 0) end)
map.createObject(27, 25).onTouch(function(player) player.teleportTo("SAFARI_ZONE_NORTH", 9, 0) end)
map.createObject(29, 3).onTouch(function(player) player.teleportTo("SAFARI_ZONE_CENTER", 0, 15) end)
map.createObject(29, 2).onTouch(function(player) player.teleportTo("SAFARI_ZONE_CENTER", 0, 14) end)
map.createObject(3, 22).onTouch(function(player) player.teleportTo("SAFARI_ZONE_SECRET_HOUSE", 2, 0) end)
map.createObject(11, 14).onTouch(function(player) player.teleportTo("SAFARI_ZONE_REST_HOUSE_2", 2, 0) end)
