map.createObject(1, 47).onTouch(function(player) player.teleportTo("VIRIDIAN_FOREST_EXIT", 4, 0) end)
map.createObject(2, 47).onTouch(function(player) player.teleportTo("VIRIDIAN_FOREST_EXIT", 5, 0) end)
map.createObject(15, -1).onTouch(function(player) player.teleportTo("VIRIDIAN_FOREST_ENTRANCE", 5, 7) end)
map.createObject(16, -1).onTouch(function(player) player.teleportTo("VIRIDIAN_FOREST_ENTRANCE", 5, 7) end)
map.createObject(17, -1).onTouch(function(player) player.teleportTo("VIRIDIAN_FOREST_ENTRANCE", 5, 7) end)
map.createObject(18, -1).onTouch(function(player) player.teleportTo("VIRIDIAN_FOREST_ENTRANCE", 5, 7) end)
