map.createObject(25, 20).setSprite("giovanni").setDirection("DOWN")--[[NO HEADER: .onUse(function(player)
    checkForTrainerBattle(player, true, "ROCKET_HIDEOUT_4_25_20", "GIOVANNI", "giovanni", {{25, "ONIX"}, {24, "RHYHORN"}, {29, "KANGASKHAN"}}, '?', '?', '?')
end)--]]
map.createObject(23, 11).setSprite("rocket").setDirection("DOWN").onUse(function(player)
    checkForTrainerBattle(player, true, "ROCKET_HIDEOUT_4_23_11", "ROCKET", "rocket", {{23, "SANDSHREW"}, {23, "EKANS"}, {23, "SANDSLASH"}}, 'I know you! You\nruined our plans\nat MT.MOON!', 'Do you have\nsomething against\nTEAM ROCKET?', 'Burned\nagain!')
end)
map.createObject(26, 11).setSprite("rocket").setDirection("DOWN").onUse(function(player)
    checkForTrainerBattle(player, true, "ROCKET_HIDEOUT_4_26_11", "ROCKET", "rocket", {{23, "EKANS"}, {23, "SANDSHREW"}, {23, "ARBOK"}}, 'How can you not\nsee the beauty of\nour evil?', "BOSS! I'm sorry I\nfailed you!", 'Ayaya!')
end)
map.createObject(11, 21).setSprite("rocket").setDirection("DOWN").onUse(function(player) possiblyBattleROCKET_HIDEOUT_4_11_21(player, true) end)
map.createObject(11, 20).onTouch(function(player) possiblyBattleROCKET_HIDEOUT_4_11_21(player, false) end)
function possiblyBattleROCKET_HIDEOUT_4_11_21(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCKET_HIDEOUT_4_11_21", "ROCKET", "rocket", {{21, "KOFFING"}, {21, "ZUBAT"}}, "The elevator\ndoesn't work? Who\nhas the LIFT KEY?", 'Oh no! I dropped\nthe LIFT KEY!', 'No!')
end
map.createObject(10, 11).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "ROCKET_HIDEOUT_4_10_11", "HP UP") end)
map.createObject(9, 19).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "ROCKET_HIDEOUT_4_9_19", "TM 02") end)
map.createObject(12, 3).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "ROCKET_HIDEOUT_4_12_3", "IRON") end)
map.createObject(25, 21).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "ROCKET_HIDEOUT_4_25_21", "SILPH SCOPE") end)
map.createObject(10, 21).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "ROCKET_HIDEOUT_4_10_21", "LIFT KEY") end)
