map.createObject(5, 22).onTouch(function(player) player.teleportTo("MT_MOON_1", 5, 30) end)
map.createObject(17, 16).onTouch(function(player) player.teleportTo("MT_MOON_3", 25, 26) end)
map.createObject(25, 18).onTouch(function(player) player.teleportTo("MT_MOON_1", 17, 24) end)
map.createObject(25, 12).onTouch(function(player) player.teleportTo("MT_MOON_1", 25, 20) end)
map.createObject(21, 10).onTouch(function(player) player.teleportTo("MT_MOON_3", 21, 18) end)
map.createObject(13, 0).onTouch(function(player) player.teleportTo("MT_MOON_3", 15, 8) end)
map.createObject(23, 24).onTouch(function(player) player.teleportTo("MT_MOON_3", 5, 28) end)
map.createObject(27, 24).onTouch(function(player) player.teleportTo("OVERWORLD", 154, 310) end)
