map.createObject(16, 17).onTouch(function(player) player.teleportTo("SILPH_CO_8F", 14, 17) end)
map.createObject(22, 17).onTouch(function(player) player.teleportTo("SILPH_CO_6F", 16, 17) end)
map.createObject(18, 17).onTouch(function(player) player.teleportTo("SILPH_CO_ELEVATOR", 1, 0) end)
map.createObject(5, 10).onTouch(function(player) player.teleportTo("SILPH_CO_11F", 3, 15) end)
map.createObject(5, 14).onTouch(function(player) player.teleportTo("SILPH_CO_3F", 11, 6) end)
map.createObject(21, 2).onTouch(function(player) player.teleportTo("SILPH_CO_5F", 27, 14) end)
