map.createObject(24, 17).onTouch(function(player) player.teleportTo("SILPH_CO_3F", 24, 17) end)
map.createObject(26, 17).onTouch(function(player) player.teleportTo("SILPH_CO_5F", 26, 17) end)
map.createObject(20, 17).onTouch(function(player) player.teleportTo("SILPH_CO_ELEVATOR", 1, 0) end)
map.createObject(11, 10).onTouch(function(player) player.teleportTo("SILPH_CO_10F", 9, 6) end)
map.createObject(17, 14).onTouch(function(player) player.teleportTo("SILPH_CO_6F", 3, 14) end)
map.createObject(3, 2).onTouch(function(player) player.teleportTo("SILPH_CO_10F", 13, 2) end)
map.createObject(17, 6).onTouch(function(player) player.teleportTo("SILPH_CO_10F", 13, 10) end)
