map.createObject(5, 29).setSprite("hiker").setDirection("DOWN").onUse(function(player) possiblyBattleMT_MOON_1_5_29(player, true) end)
map.createObject(5, 28).onTouch(function(player) possiblyBattleMT_MOON_1_5_29(player, false) end)
map.createObject(5, 27).onTouch(function(player) possiblyBattleMT_MOON_1_5_29(player, false) end)
function possiblyBattleMT_MOON_1_5_29(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "MT_MOON_1_5_29", "HIKER", "hiker", {{10, "GEODUDE"}, {10, "GEODUDE"}, {10, "ONIX"}}, "WHOA! You shocked\nme! Oh, you're\njust a kid!", "Kids like you\nshouldn't be\nhere!", 'Wow!\nShocked again!')
end
map.createObject(12, 19).setSprite("bug_catcher").setDirection("RIGHT").onUse(function(player) possiblyBattleMT_MOON_1_12_19(player, true) end)
map.createObject(13, 19).onTouch(function(player) possiblyBattleMT_MOON_1_12_19(player, false) end)
map.createObject(14, 19).onTouch(function(player) possiblyBattleMT_MOON_1_12_19(player, false) end)
map.createObject(15, 19).onTouch(function(player) possiblyBattleMT_MOON_1_12_19(player, false) end)
function possiblyBattleMT_MOON_1_12_19(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "MT_MOON_1_12_19", "YOUNGSTER", "youngster", {{10, "RATTATA"}, {10, "RATTATA"}, {10, "ZUBAT"}}, 'Did you come to\nexplore too?', 'I came down here\nto show off to\ngirls.', 'Losing\nstinks!')
end
map.createObject(30, 31).setSprite("lass").setDirection("DOWN").onUse(function(player) possiblyBattleMT_MOON_1_30_31(player, true) end)
map.createObject(30, 30).onTouch(function(player) possiblyBattleMT_MOON_1_30_31(player, false) end)
map.createObject(30, 29).onTouch(function(player) possiblyBattleMT_MOON_1_30_31(player, false) end)
map.createObject(30, 28).onTouch(function(player) possiblyBattleMT_MOON_1_30_31(player, false) end)
function possiblyBattleMT_MOON_1_30_31(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "MT_MOON_1_30_31", "LASS", "lass", {{11, "ODDISH"}, {11, "BELLSPROUT"}}, "Wow! It's way\nbigger in here\nthan I thought!", 'How do you get\nout of here?', 'Oh!\nI lost it!')
end
map.createObject(24, 4).setSprite("black_hair_boy_2").setDirection("UP").onUse(function(player) possiblyBattleMT_MOON_1_24_4(player, true) end)
map.createObject(24, 5).onTouch(function(player) possiblyBattleMT_MOON_1_24_4(player, false) end)
map.createObject(24, 6).onTouch(function(player) possiblyBattleMT_MOON_1_24_4(player, false) end)
map.createObject(24, 7).onTouch(function(player) possiblyBattleMT_MOON_1_24_4(player, false) end)
function possiblyBattleMT_MOON_1_24_4(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "MT_MOON_1_24_4", "SUPER NERD", "supernerd", {{11, "MAGNEMITE"}, {11, "VOLTORB"}}, "What! Don't sneak\nup on me!", 'I have to find\nstronger POKEMON.', "My\nPOKEMON won't do!")
end
map.createObject(16, 12).setSprite("lass").setDirection("DOWN").onUse(function(player) possiblyBattleMT_MOON_1_16_12(player, true) end)
map.createObject(16, 11).onTouch(function(player) possiblyBattleMT_MOON_1_16_12(player, false) end)
map.createObject(16, 10).onTouch(function(player) possiblyBattleMT_MOON_1_16_12(player, false) end)
map.createObject(16, 9).onTouch(function(player) possiblyBattleMT_MOON_1_16_12(player, false) end)
function possiblyBattleMT_MOON_1_16_12(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "MT_MOON_1_16_12", "LASS", "lass", {{14, "CLEFAIRY"}}, "What? I'm waiting\nfor my friends to\nfind me here.", 'I heard there are\nsome very rare\nfossils here.', 'I lost?')
end
map.createObject(7, 13).setSprite("bug_catcher").setDirection("DOWN").onUse(function(player) possiblyBattleMT_MOON_1_7_13(player, true) end)
map.createObject(7, 12).onTouch(function(player) possiblyBattleMT_MOON_1_7_13(player, false) end)
map.createObject(7, 11).onTouch(function(player) possiblyBattleMT_MOON_1_7_13(player, false) end)
map.createObject(7, 10).onTouch(function(player) possiblyBattleMT_MOON_1_7_13(player, false) end)
function possiblyBattleMT_MOON_1_7_13(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "MT_MOON_1_7_13", "BUG CATCHER", "bugcatcher", {{11, "WEEDLE"}, {11, "KAKUNA"}}, 'Suspicious men\nare in the cave.\nWhat about you?', "I saw them! I'm\nsure they're from\nTEAM ROCKET!", 'You\ngot me!')
end
map.createObject(30, 8).setSprite("bug_catcher").setDirection("RIGHT").onUse(function(player) possiblyBattleMT_MOON_1_30_8(player, true) end)
map.createObject(31, 8).onTouch(function(player) possiblyBattleMT_MOON_1_30_8(player, false) end)
map.createObject(32, 8).onTouch(function(player) possiblyBattleMT_MOON_1_30_8(player, false) end)
map.createObject(33, 8).onTouch(function(player) possiblyBattleMT_MOON_1_30_8(player, false) end)
function possiblyBattleMT_MOON_1_30_8(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "MT_MOON_1_30_8", "BUG CATCHER", "bugcatcher", {{10, "CATERPIE"}, {10, "METAPOD"}, {10, "CATERPIE"}}, 'Go through this\ncave to get to\nCERULEAN CITY!', 'ZUBAT is tough!\nBut, it can be\nuseful if you\ncatch one.', 'I\nlost.')
end
map.createObject(2, 15).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "MT_MOON_1_2_15", "POTION") end)
map.createObject(2, 33).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "MT_MOON_1_2_33", "MOON STONE") end)
map.createObject(35, 4).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "MT_MOON_1_35_4", "RARE CANDY") end)
map.createObject(36, 12).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "MT_MOON_1_36_12", "ESCAPE ROPE") end)
map.createObject(20, 2).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "MT_MOON_1_20_2", "POTION") end)
map.createObject(5, 3).setSprite("ball").onUse(function(player) attemptToPickupObject(player, "MT_MOON_1_5_3", "TM 12") end)
map.setAlwaysWildEncounters()
map.setWildPokemon({0, 0}, {39, 35}, 0.0392157).type("LAND").add(51, 8, "ZUBAT").add(51, 7, "ZUBAT").add(39, 9, "ZUBAT").add(25, 8, "GEODUDE").add(25, 6, "ZUBAT").add(25, 10, "ZUBAT").add(13, 10, "GEODUDE").add(13, 8, "PARAS").add(11, 11, "ZUBAT").add(3, 8, "CLEFAIRY")
