map.createObject(16, 17).onTouch(function(player) player.teleportTo("SILPH_CO_7F", 22, 17) end)
map.createObject(14, 17).onTouch(function(player) player.teleportTo("SILPH_CO_5F", 24, 17) end)
map.createObject(18, 17).onTouch(function(player) player.teleportTo("SILPH_CO_ELEVATOR", 1, 0) end)
map.createObject(3, 14).onTouch(function(player) player.teleportTo("SILPH_CO_4F", 17, 14) end)
map.createObject(23, 14).onTouch(function(player) player.teleportTo("SILPH_CO_2F", 9, 2) end)
