map.createObject(16, 17).onTouch(function(player) player.teleportTo("SILPH_CO_9F", 16, 17) end)
map.createObject(14, 17).onTouch(function(player) player.teleportTo("SILPH_CO_7F", 16, 17) end)
map.createObject(18, 17).onTouch(function(player) player.teleportTo("SILPH_CO_ELEVATOR", 1, 0) end)
map.createObject(3, 6).onTouch(function(player) player.teleportTo("SILPH_CO_8F", 11, 8) end)
map.createObject(3, 2).onTouch(function(player) player.teleportTo("SILPH_CO_2F", 13, 14) end)
map.createObject(11, 12).onTouch(function(player) player.teleportTo("SILPH_CO_2F", 27, 2) end)
map.createObject(11, 8).onTouch(function(player) player.teleportTo("SILPH_CO_8F", 3, 6) end)
