map.createObject(0, 21).onTouch(function(player) player.teleportTo("SAFARI_ZONE_NORTH", 39, 5) end)
map.createObject(0, 20).onTouch(function(player) player.teleportTo("SAFARI_ZONE_NORTH", 39, 4) end)
map.createObject(0, 3).onTouch(function(player) player.teleportTo("SAFARI_ZONE_CENTER", 29, 15) end)
map.createObject(0, 2).onTouch(function(player) player.teleportTo("SAFARI_ZONE_CENTER", 29, 15) end)
map.createObject(25, 16).onTouch(function(player) player.teleportTo("SAFARI_ZONE_REST_HOUSE_3", 2, 0) end)
