map.createObject(6, 4).setSprite("fisher2").setDirection("LEFT")--[[['1 ; person']--]]
map.createObject(1, 4).setSprite("girl").setDirection("RIGHT")--[[['2 ; person']--]]
map.createObject(6, 3).setSprite("clefairy").setDirection("LEFT")--[[['3 ; person']--]]
map.createObject(1, 3).setSprite("seel").setDirection("RIGHT")--[[['4 ; person']--]]
map.createObject(3, 6).setSprite("gentleman").setDirection("DOWN")--[[['5 ; person']--]]
map.createObject(5, 6).setSprite("cable_club_woman").setDirection("DOWN")--[[['6 ; person']--]]
