map.createObject(11, 22).setSprite("lass").setDirection("DOWN").onUse(function(player) possiblyBattleROCK_TUNNEL_2_11_22(player, true) end)
map.createObject(11, 21).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_11_22(player, false) end)
map.createObject(11, 20).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_11_22(player, false) end)
map.createObject(11, 19).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_11_22(player, false) end)
map.createObject(11, 18).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_11_22(player, false) end)
function possiblyBattleROCK_TUNNEL_2_11_22(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_2_11_22", "JR.TRAINER#FEMALE", "jr.trainerf", {{21, "JIGGLYPUFF"}, {21, "PIDGEY"}, {21, "MEOWTH"}}, 'Hikers leave twigs\nas trail markers.', 'I want to go \nhome!', 'Ohhh!\nI did my best!')
end
map.createObject(6, 25).setSprite("hiker").setDirection("DOWN").onUse(function(player) possiblyBattleROCK_TUNNEL_2_6_25(player, true) end)
map.createObject(6, 24).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_6_25(player, false) end)
map.createObject(6, 23).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_6_25(player, false) end)
map.createObject(6, 22).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_6_25(player, false) end)
function possiblyBattleROCK_TUNNEL_2_6_25(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_2_6_25", "HIKER", "hiker", {{21, "GEODUDE"}, {21, "GEODUDE"}, {21, "GRAVELER"}}, 'Hahaha! Can you\nbeat my power?', 'I go for power\nbecause I hate\nthinking!', 'Oops!\nOut-muscled!')
end
map.createObject(3, 30).setSprite("black_hair_boy_2").setDirection("DOWN").onUse(function(player) possiblyBattleROCK_TUNNEL_2_3_30(player, true) end)
map.createObject(3, 29).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_3_30(player, false) end)
map.createObject(3, 28).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_3_30(player, false) end)
map.createObject(3, 27).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_3_30(player, false) end)
function possiblyBattleROCK_TUNNEL_2_3_30(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_2_3_30", "POKEMANIAC", "pokemaniac", {{20, "SLOWPOKE"}, {20, "SLOWPOKE"}, {20, "SLOWPOKE"}}, 'You have a\nPOKEDEX?\nI want one too!', 'When you finish\nyour POKEDEX, can\nI have it?', "Shoot!\nI'm so jealous!")
end
map.createObject(20, 14).setSprite("black_hair_boy_2").setDirection("RIGHT").onUse(function(player) possiblyBattleROCK_TUNNEL_2_20_14(player, true) end)
map.createObject(21, 14).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_20_14(player, false) end)
map.createObject(22, 14).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_20_14(player, false) end)
map.createObject(23, 14).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_20_14(player, false) end)
map.createObject(24, 14).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_20_14(player, false) end)
function possiblyBattleROCK_TUNNEL_2_20_14(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_2_20_14", "POKEMANIAC", "pokemaniac", {{22, "CHARMANDER"}, {22, "CUBONE"}}, 'Do you know about\ncostume players?', 'Costume players\ndress up as\nPOKEMON for fun.', "Well,\nthat's that.")
end
map.createObject(30, 25).setSprite("hiker").setDirection("DOWN").onUse(function(player) possiblyBattleROCK_TUNNEL_2_30_25(player, true) end)
map.createObject(30, 24).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_30_25(player, false) end)
map.createObject(30, 23).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_30_25(player, false) end)
map.createObject(30, 22).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_30_25(player, false) end)
function possiblyBattleROCK_TUNNEL_2_30_25(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_2_30_25", "HIKER", "hiker", {{25, "GEODUDE"}}, 'My POKEMON\ntechniques will\nleave you crying!', "In mountains,\nyou'll often find\nrock-type POKEMON.", "I give!\nYou're a better\ntechnician!")
end
map.createObject(14, 7).setSprite("lass").setDirection("RIGHT").onUse(function(player) possiblyBattleROCK_TUNNEL_2_14_7(player, true) end)
map.createObject(15, 7).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_14_7(player, false) end)
map.createObject(16, 7).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_14_7(player, false) end)
map.createObject(17, 7).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_14_7(player, false) end)
map.createObject(18, 7).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_14_7(player, false) end)
function possiblyBattleROCK_TUNNEL_2_14_7(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_2_14_7", "JR.TRAINER#FEMALE", "jr.trainerf", {{22, "ODDISH"}, {22, "BULBASAUR"}}, "I don't often\ncome here, but I\nwill fight you.", 'I like tiny\nPOKEMON, big ones\nare too scary!', 'Oh!\nI lost!')
end
map.createObject(33, 30).setSprite("hiker").setDirection("RIGHT").onUse(function(player) possiblyBattleROCK_TUNNEL_2_33_30(player, true) end)
map.createObject(34, 30).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_33_30(player, false) end)
map.createObject(35, 30).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_33_30(player, false) end)
map.createObject(36, 30).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_33_30(player, false) end)
function possiblyBattleROCK_TUNNEL_2_33_30(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_2_33_30", "HIKER", "hiker", {{20, "MACHOP"}, {20, "ONIX"}}, 'Hit me with your\nbest shot!', "I'll raise my\nPOKEMON to beat\nyours, kid!", 'Fired\naway!')
end
map.createObject(26, 5).setSprite("black_hair_boy_2").setDirection("DOWN").onUse(function(player) possiblyBattleROCK_TUNNEL_2_26_5(player, true) end)
map.createObject(26, 4).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_26_5(player, false) end)
map.createObject(26, 3).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_26_5(player, false) end)
map.createObject(26, 2).onTouch(function(player) possiblyBattleROCK_TUNNEL_2_26_5(player, false) end)
function possiblyBattleROCK_TUNNEL_2_26_5(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_2_26_5", "POKEMANIAC", "pokemaniac", {{25, "SLOWPOKE"}}, "I draw POKEMON\nwhen I'm home.", "I'm an artist,\nnot a fighter.", "Whew!\nI'm exhausted!")
end
map.setAlwaysWildEncounters()
map.setWildPokemon({0, 0}, {39, 35}, 0.0588235).type("LAND").add(51, 16, "ZUBAT").add(51, 17, "ZUBAT").add(39, 17, "GEODUDE").add(25, 15, "MACHOP").add(25, 16, "GEODUDE").add(25, 18, "ZUBAT").add(13, 17, "MACHOP").add(13, 17, "ONIX").add(11, 13, "ONIX").add(3, 18, "GEODUDE")
