map.createObject(0, 5).onTouch(function(player) player.teleportTo("OVERWORLD", 207, 73) end)
map.createObject(0, 4).onTouch(function(player) player.teleportTo("OVERWORLD", 207, 72) end)
map.createObject(7, 5).onTouch(function(player) player.teleportTo("OVERWORLD", 214, 73) end)
map.createObject(7, 4).onTouch(function(player) player.teleportTo("OVERWORLD", 214, 72) end)
map.createObject(6, 1).onTouch(function(player) player.teleportTo("ROUTE_15_GATE_2F", 7, 0) end)
