map.createObject(7, 30).setSprite("hiker").setDirection("DOWN").onUse(function(player) possiblyBattleROCK_TUNNEL_1_7_30(player, true) end)
map.createObject(7, 29).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_7_30(player, false) end)
map.createObject(7, 28).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_7_30(player, false) end)
map.createObject(7, 27).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_7_30(player, false) end)
map.createObject(7, 26).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_7_30(player, false) end)
function possiblyBattleROCK_TUNNEL_1_7_30(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_1_7_30", "HIKER", "hiker", {{19, "GEODUDE"}, {19, "MACHOP"}, {19, "GEODUDE"}, {19, "GEODUDE"}}, 'This tunnel goes\na long way, kid!', 'Watch for ONIX!\nIt can put the\nsqueeze on you!', 'Doh!\nYou win!')
end
map.createObject(5, 19).setSprite("hiker").setDirection("DOWN").onUse(function(player) possiblyBattleROCK_TUNNEL_1_5_19(player, true) end)
map.createObject(5, 18).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_5_19(player, false) end)
map.createObject(5, 17).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_5_19(player, false) end)
map.createObject(5, 16).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_5_19(player, false) end)
map.createObject(5, 15).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_5_19(player, false) end)
function possiblyBattleROCK_TUNNEL_1_5_19(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_1_5_19", "HIKER", "hiker", {{20, "ONIX"}, {20, "ONIX"}, {20, "GEODUDE"}}, "Hmm. Maybe I'm\nlost in here...", 'That sleeping\nPOKEMON on ROUTE\n12 forced me to\ntake this detour.', 'Ease up!\nWhat am I doing?\nWhich way is out?')
end
map.createObject(17, 20).setSprite("hiker").setDirection("LEFT").onUse(function(player) possiblyBattleROCK_TUNNEL_1_17_20(player, true) end)
map.createObject(16, 20).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_17_20(player, false) end)
map.createObject(15, 20).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_17_20(player, false) end)
map.createObject(14, 20).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_17_20(player, false) end)
function possiblyBattleROCK_TUNNEL_1_17_20(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_1_17_20", "HIKER", "hiker", {{21, "GEODUDE"}, {21, "GRAVELER"}}, 'Outsiders like\nyou need to show\nme some respect!', "You're talented\nenough to hike!", 'I give!')
end
map.createObject(23, 27).setSprite("black_hair_boy_2").setDirection("LEFT").onUse(function(player) possiblyBattleROCK_TUNNEL_1_23_27(player, true) end)
map.createObject(22, 27).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_23_27(player, false) end)
map.createObject(21, 27).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_23_27(player, false) end)
map.createObject(20, 27).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_23_27(player, false) end)
function possiblyBattleROCK_TUNNEL_1_23_27(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_1_23_27", "POKEMANIAC", "pokemaniac", {{23, "CUBONE"}, {23, "SLOWPOKE"}}, 'POKEMON fight!\nReady, go!', "Oh well, I'll get\na ZUBAT as I go!", 'Game\nover!')
end
map.createObject(37, 14).setSprite("lass").setDirection("LEFT").onUse(function(player) possiblyBattleROCK_TUNNEL_1_37_14(player, true) end)
map.createObject(36, 14).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_37_14(player, false) end)
map.createObject(35, 14).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_37_14(player, false) end)
map.createObject(34, 14).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_37_14(player, false) end)
map.createObject(33, 14).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_37_14(player, false) end)
function possiblyBattleROCK_TUNNEL_1_37_14(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_1_37_14", "JR.TRAINER#FEMALE", "jr.trainerf", {{22, "BELLSPROUT"}, {22, "CLEFAIRY"}}, "Eek! Don't try\nanything funny in\nthe dark!", 'I saw a MACHOP\nin this tunnel!', 'It\nwas too dark!')
end
map.createObject(22, 11).setSprite("lass").setDirection("DOWN").onUse(function(player) possiblyBattleROCK_TUNNEL_1_22_11(player, true) end)
map.createObject(22, 10).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_22_11(player, false) end)
map.createObject(22, 9).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_22_11(player, false) end)
map.createObject(22, 8).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_22_11(player, false) end)
map.createObject(22, 7).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_22_11(player, false) end)
function possiblyBattleROCK_TUNNEL_1_22_11(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_1_22_11", "JR.TRAINER#FEMALE", "jr.trainerf", {{20, "MEOWTH"}, {20, "ODDISH"}, {20, "PIDGEY"}}, 'I came this far\nfor POKEMON!', 'You looked cute\nand harmless!', "I'm\nout of POKEMON!")
end
map.createObject(32, 11).setSprite("lass").setDirection("RIGHT").onUse(function(player) possiblyBattleROCK_TUNNEL_1_32_11(player, true) end)
map.createObject(33, 11).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_32_11(player, false) end)
map.createObject(34, 11).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_32_11(player, false) end)
map.createObject(35, 11).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_32_11(player, false) end)
map.createObject(36, 11).onTouch(function(player) possiblyBattleROCK_TUNNEL_1_32_11(player, false) end)
function possiblyBattleROCK_TUNNEL_1_32_11(player, is_talked_to)
    checkForTrainerBattle(player, is_talked_to, "ROCK_TUNNEL_1_32_11", "JR.TRAINER#FEMALE", "jr.trainerf", {{19, "PIDGEY"}, {19, "RATTATA"}, {19, "RATTATA"}, {19, "BELLSPROUT"}}, "You have POKEMON!\nLet's start!", "Whew! I'm all\nsweaty now!", 'You\nplay hard!')
end
map.setAlwaysWildEncounters()
map.setWildPokemon({0, 0}, {39, 35}, 0.0588235).type("LAND").add(51, 16, "ZUBAT").add(51, 17, "ZUBAT").add(39, 17, "GEODUDE").add(25, 15, "MACHOP").add(25, 16, "GEODUDE").add(25, 18, "ZUBAT").add(13, 15, "ZUBAT").add(13, 17, "MACHOP").add(11, 13, "ONIX").add(3, 15, "ONIX")
