map.createObject(2, -1).onTouch(function(player) player.teleportTo("OVERWORLD", 158, 238) end)
map.createObject(3, -1).onTouch(function(player) player.teleportTo("OVERWORLD", 158, 238) end)
map.createObject(16, -1).onTouch(function(player) player.teleportTo("OVERWORLD", 160, 238) end)
map.createObject(17, -1).onTouch(function(player) player.teleportTo("OVERWORLD", 160, 238) end)
map.createObject(12, 6).onTouch(function(player) player.teleportTo("CELADON_MART_2", 12, 6) end)
map.createObject(1, 6).onTouch(function(player) player.teleportTo("CELADON_MART_ELEVATOR", 1, 0) end)
